version: "3.8"
services:
  db:
    image: postgres:16
    container_name: db_app
    env_file:
      - .env-db

  db_test:
    image: postgres:16
    container_name: db_app_test
    env_file:
      - .env-db-test

  app:
    build:
      context: .
    env_file:
      - .env-app
    container_name: app
    command: ["docker/app.sh"]
    restart: always
    ports:
      - 7999:8000
    depends_on:
      - db