"""update table couriers & create tables districts order couriers_dustrict

Revision ID: d9346e911fa3
Revises: f6d6f0fd8ac9
Create Date: 2024-01-16 13:59:48.780629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9346e911fa3'
down_revision: Union[str, None] = 'f6d6f0fd8ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('couriers_districts',
    sa.Column('courier_id', sa.UUID(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('courier_id', 'district_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('courier_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('date_publication', sa.DateTime(), nullable=True),
    sa.Column('date_completion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('couriers', sa.Column('avg_order_complete_time', sa.DateTime(), nullable=True))
    op.add_column('couriers', sa.Column('avg_day_orders', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('couriers', 'avg_day_orders')
    op.drop_column('couriers', 'avg_order_complete_time')
    op.drop_table('orders')
    op.drop_table('couriers_districts')
    op.drop_table('districts')
    # ### end Alembic commands ###
