"""update couriers 2

Revision ID: 28f5fda31b83
Revises: e29221db72f0
Create Date: 2024-01-16 16:48:45.782291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28f5fda31b83'
down_revision: Union[str, None] = 'e29221db72f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'districts', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'districts', type_='unique')
    # ### end Alembic commands ###
